{"uuid": "f252e9e8-4d44-4ea0-9bb9-1cd576f7abf3", "children": ["28d1d8d4-4bbd-465b-94b5-9dd3511ad960"], "befores": [{"name": "function_user", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for CreateUserResponseSchema\nuser\n  Field required [type=missing, input_value={'detail': 'User with ema...ple.net already exists'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing\n", "trace": "  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/Desktop/autotests-api/fixtures/users.py\", line 40, in function_user\n    response = public_users_client.create_user(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/Desktop/autotests-api/clients/users/public_users_client.py\", line 28, in create_user\n    return CreateUserResponseSchema.model_validate_json(response.text)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/Desktop/autotests-api/.venv/lib/python3.12/site-packages/pydantic/main.py\", line 746, in model_validate_json\n    return cls.__pydantic_validator__.validate_json(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Create user", "status": "passed", "steps": [{"name": "Make POST request to '/api/v1/users'", "status": "passed", "attachments": [{"name": "cURL command", "source": "53db9c15-e788-4408-a7bf-878cc1a6d67c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "url", "value": "'/api/v1/users'"}, {"name": "json", "value": "{'email': 'trodriguez@example.net', 'password': '_8oSb(ujq9', 'lastName': 'Stewart', 'firstName': 'Brian', 'middleName': 'Thomas'}"}, {"name": "data", "value": "None"}, {"name": "files", "value": "None"}], "start": 1756415544293, "stop": 1756415544297}], "parameters": [{"name": "request", "value": "CreateUserRequestSchema(email='trodriguez@example.net', password='_8oSb(ujq9', last_name='Stewart', first_name='Brian', middle_name='Thomas')"}], "start": 1756415544293, "stop": 1756415544297}], "start": 1756415544292, "stop": 1756415544297}], "start": 1756415544292, "stop": 1756415544321}